# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\x12\x08math_api\"\x1f\n\x07request\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x1a\n\x08response\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32t\n\x08\x41\x64\x64ition\x12.\n\x03\x61\x64\x64\x12\x11.math_api.request\x1a\x12.math_api.response\"\x00\x12\x38\n\x0b\x61\x64\x64Streamer\x12\x11.math_api.request\x1a\x12.math_api.response\"\x00\x30\x01\x42\tZ\x07./protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\007./proto'
  _globals['_REQUEST']._serialized_start=23
  _globals['_REQUEST']._serialized_end=54
  _globals['_RESPONSE']._serialized_start=56
  _globals['_RESPONSE']._serialized_end=82
  _globals['_ADDITION']._serialized_start=84
  _globals['_ADDITION']._serialized_end=200
# @@protoc_insertion_point(module_scope)
