// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: api.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AdditionClient is the client API for Addition service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdditionClient interface {
	// A simple RPC.
	//
	// Gets two numbers and returns the sum of those numbers.
	Add(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	// A server-to-client streaming RPC.
	//
	// Gets two numbers and streams the response 3 times (adding the result to the last result every time) to the client.
	AddStreamer(ctx context.Context, in *Request, opts ...grpc.CallOption) (Addition_AddStreamerClient, error)
}

type additionClient struct {
	cc grpc.ClientConnInterface
}

func NewAdditionClient(cc grpc.ClientConnInterface) AdditionClient {
	return &additionClient{cc}
}

func (c *additionClient) Add(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/math_api.Addition/add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *additionClient) AddStreamer(ctx context.Context, in *Request, opts ...grpc.CallOption) (Addition_AddStreamerClient, error) {
	stream, err := c.cc.NewStream(ctx, &Addition_ServiceDesc.Streams[0], "/math_api.Addition/addStreamer", opts...)
	if err != nil {
		return nil, err
	}
	x := &additionAddStreamerClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Addition_AddStreamerClient interface {
	Recv() (*Response, error)
	grpc.ClientStream
}

type additionAddStreamerClient struct {
	grpc.ClientStream
}

func (x *additionAddStreamerClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AdditionServer is the server API for Addition service.
// All implementations must embed UnimplementedAdditionServer
// for forward compatibility
type AdditionServer interface {
	// A simple RPC.
	//
	// Gets two numbers and returns the sum of those numbers.
	Add(context.Context, *Request) (*Response, error)
	// A server-to-client streaming RPC.
	//
	// Gets two numbers and streams the response 3 times (adding the result to the last result every time) to the client.
	AddStreamer(*Request, Addition_AddStreamerServer) error
	mustEmbedUnimplementedAdditionServer()
}

// UnimplementedAdditionServer must be embedded to have forward compatible implementations.
type UnimplementedAdditionServer struct {
}

func (UnimplementedAdditionServer) Add(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedAdditionServer) AddStreamer(*Request, Addition_AddStreamerServer) error {
	return status.Errorf(codes.Unimplemented, "method AddStreamer not implemented")
}
func (UnimplementedAdditionServer) mustEmbedUnimplementedAdditionServer() {}

// UnsafeAdditionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdditionServer will
// result in compilation errors.
type UnsafeAdditionServer interface {
	mustEmbedUnimplementedAdditionServer()
}

func RegisterAdditionServer(s grpc.ServiceRegistrar, srv AdditionServer) {
	s.RegisterService(&Addition_ServiceDesc, srv)
}

func _Addition_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdditionServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/math_api.Addition/add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdditionServer).Add(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Addition_AddStreamer_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AdditionServer).AddStreamer(m, &additionAddStreamerServer{stream})
}

type Addition_AddStreamerServer interface {
	Send(*Response) error
	grpc.ServerStream
}

type additionAddStreamerServer struct {
	grpc.ServerStream
}

func (x *additionAddStreamerServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

// Addition_ServiceDesc is the grpc.ServiceDesc for Addition service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Addition_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "math_api.Addition",
	HandlerType: (*AdditionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "add",
			Handler:    _Addition_Add_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "addStreamer",
			Handler:       _Addition_AddStreamer_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api.proto",
}
